// packages/example-vue/src/App.vue
<script setup lang="ts">
import { GhostTrash, OutlineTrash, SolidTrash } from '@scarlab-icons/vue'
</script>

<template>
  <GhostTrash width="300" height="300" color="white" />
  <OutlineTrash width="300" height="300" color="white" />
  <SolidTrash width="300" height="300" color="white" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/example-react/src/App.tsx
import { SolidTrash, OutlineTrash, GhostTrash } from '@scarlab-icons/react'
import './App.css'

function App() {
  return (
    <>
        <GhostTrash width="300" height="300" color="white" />
        <OutlineTrash width="300" height="300" color="white" />
        <SolidTrash width="300" height="300" color="white" />
    </>
  )
}

export default App
