// react/outline/adjustments.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-adjustments" {...props}>
    <path d="M5 3L5 15" />
	<path d="M5 19L5 21" />
	<path d="M12 3L12 5" />
	<path d="M19 19L19 21" />
	<path d="M12 9L12 21" />
	<path d="M19 3V15" />
	<path d="M14 7C14 8.10457 13.1046 9 12 9C10.8954 9 10 8.10457 10 7C10 5.89543 10.8954 5 12 5C13.1046 5 14 5.89543 14 7Z" />
	<path d="M21 17C21 18.1046 20.1046 19 19 19C17.8954 19 17 18.1046 17 17C17 15.8954 17.8954 15 19 15C20.1046 15 21 15.8954 21 17Z" />
	<path d="M7 17C7 18.1046 6.10457 19 5 19C3.89543 19 3 18.1046 3 17C3 15.8954 3.89543 15 5 15C6.10457 15 7 15.8954 7 17Z" />
  </svg>
}

export default SvgComponent

// vue/solid/adjustments.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-adjustments",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C12.5523 2 13 2.44772 13 3V4.17071C14.1652 4.58254 15 5.69378 15 7C15 8.30622 14.1652 9.41746 13 9.82929L13 21C13 21.5523 12.5523 22 12 22C11.4477 22 11 21.5523 11 21L11 9.82929C9.83481 9.41746 9 8.30622 9 7C9 5.69378 9.83481 4.58254 11 4.17071V3C11 2.44772 11.4477 2 12 2Z"}), 
	_createElementVNode("path", {"d":"M19 2C19.5523 2 20 2.44772 20 3V14.1707C21.1652 14.5825 22 15.6938 22 17C22 18.3062 21.1652 19.4175 20 19.8293V21C20 21.5523 19.5523 22 19 22C18.4477 22 18 21.5523 18 21V19.8293C16.8348 19.4175 16 18.3062 16 17C16 15.6938 16.8348 14.5825 18 14.1707V3C18 2.44772 18.4477 2 19 2Z"}), 
	_createElementVNode("path", {"d":"M5 2C5.55228 2 6 2.44772 6 3V14.1707C7.16519 14.5825 8 15.6938 8 17C8 18.3062 7.16519 19.4175 6 19.8293V21C6 21.5523 5.55228 22 5 22C4.44772 22 4 21.5523 4 21V19.8293C2.83481 19.4175 2 18.3062 2 17C2 15.6938 2.83481 14.5825 4 14.1707V3C4 2.44772 4.44772 2 5 2Z"})
  ]))
}
