// react/outline/aperture.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-aperture" {...props}>
    <path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
	<path d="M3.59998 15H14.15" />
	<path d="M6.55115 4.93823L9.81128 14.9719" />
	<path d="M17.0323 4.6355L8.49722 10.8366" />
	<path d="M20.5591 14.5104L12.024 8.30924" />
	<path d="M12.2574 20.9159L15.5176 10.8822" />
  </svg>
}

export default SvgComponent

// vue/solid/aperture.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-aperture",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM6 14C5.44772 14 5 14.4477 5 15C5 15.5523 5.44772 16 6 16H12.8033L11.9289 18.691C11.7582 19.2162 12.0457 19.7804 12.571 19.9511C13.0962 20.1217 13.6604 19.8343 13.831 19.309L16.0525 12.4722L18.4122 14.1866C18.859 14.5112 19.4844 14.4122 19.809 13.9654C20.1336 13.5186 20.0346 12.8932 19.5878 12.5686L13.7013 8.29179L15.7421 6.80902C16.189 6.48439 16.288 5.85902 15.9634 5.41221C15.6388 4.96541 15.0134 4.86636 14.5666 5.19098L8.99906 9.23601L8.17213 6.69098C8.00147 6.16573 7.43731 5.87828 6.91206 6.04894C6.38681 6.21961 6.09935 6.78376 6.27002 7.30902L8.44405 14H6ZM14.3512 11.2361L12 9.52786L9.6489 11.236L10.547 14H13.4531L14.3512 11.2361Z"})
  ]))
}
