// react/outline/apps.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-apps" {...props}>
    <path d="M3 6.0296C3 3.53472 3.53472 3 6.0296 3H6.9704C9.46528 3 10 3.53472 10 6.0296V6.9704C10 9.46528 9.46528 10 6.9704 10H6.0296C3.53472 10 3 9.46528 3 6.9704V6.0296Z" />
	<path d="M3 17.0296C3 14.5347 3.53472 14 6.0296 14H6.9704C9.46528 14 10 14.5347 10 17.0296V17.9704C10 20.4653 9.46528 21 6.9704 21H6.0296C3.53472 21 3 20.4653 3 17.9704V17.0296Z" />
	<path d="M14 17.0296C14 14.5347 14.5347 14 17.0296 14H17.9704C20.4653 14 21 14.5347 21 17.0296V17.9704C21 20.4653 20.4653 21 17.9704 21H17.0296C14.5347 21 14 20.4653 14 17.9704V17.0296Z" />
	<path d="M14 6.5H21" />
	<path d="M17.5 3V10" />
  </svg>
}

export default SvgComponent

// vue/solid/apps.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-apps",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 5.8952C2 2.6875 2.6875 2 5.8952 2H7.1048C10.3125 2 11 2.6875 11 5.8952V7.1048C11 10.3125 10.3125 11 7.1048 11H5.8952C2.6875 11 2 10.3125 2 7.1048V5.8952Z"}), 
	_createElementVNode("path", {"d":"M2 16.8952C2 13.6875 2.6875 13 5.8952 13H7.1048C10.3125 13 11 13.6875 11 16.8952V18.1048C11 21.3125 10.3125 22 7.1048 22H5.8952C2.6875 22 2 21.3125 2 18.1048V16.8952Z"}), 
	_createElementVNode("path", {"d":"M13 16.8952C13 13.6875 13.6875 13 16.8952 13H18.1048C21.3125 13 22 13.6875 22 16.8952V18.1048C22 21.3125 21.3125 22 18.1048 22H16.8952C13.6875 22 13 21.3125 13 18.1048V16.8952Z"}), 
	_createElementVNode("path", {"d":"M18.5 3C18.5 2.44772 18.0523 2 17.5 2C16.9477 2 16.5 2.44772 16.5 3V5.5H14C13.4477 5.5 13 5.94772 13 6.5C13 7.05228 13.4477 7.5 14 7.5H16.5V10C16.5 10.5523 16.9477 11 17.5 11C18.0523 11 18.5 10.5523 18.5 10V7.5H21C21.5523 7.5 22 7.05228 22 6.5C22 5.94772 21.5523 5.5 21 5.5H18.5V3Z"})
  ]))
}
