// react/solid/arrow-down-left-circle.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-arrow-down-left-circle" {...props}>
    <path d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM14.2929 8.29289C14.6834 7.90237 15.3166 7.90237 15.7071 8.29289C16.0976 8.68342 16.0976 9.31658 15.7071 9.70711L11.4142 14H14C14.5523 14 15 14.4477 15 15C15 15.5523 14.5523 16 14 16H9.32833C8.59458 16 8 15.4051 8 14.6716V10C8 9.44772 8.44772 9 9 9C9.55228 9 10 9.44772 10 10V12.5858L14.2929 8.29289Z" />
  </svg>
}

export default SvgComponent

// vue/solid/arrow-down-left-circle.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-arrow-down-left-circle",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM14.2929 8.29289C14.6834 7.90237 15.3166 7.90237 15.7071 8.29289C16.0976 8.68342 16.0976 9.31658 15.7071 9.70711L11.4142 14H14C14.5523 14 15 14.4477 15 15C15 15.5523 14.5523 16 14 16H9.32833C8.59458 16 8 15.4051 8 14.6716V10C8 9.44772 8.44772 9 9 9C9.55228 9 10 9.44772 10 10V12.5858L14.2929 8.29289Z"})
  ]))
}
