// react/solid/bookmark.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-bookmark" {...props}>
    <path d="M7.0999 2.20071C7.81792 2.04874 8.66947 2 9.648 2H14.352C15.3305 2 16.1821 2.04874 16.9001 2.20071C17.6269 2.35454 18.2814 2.62734 18.801 3.12219C19.8286 4.10082 20 5.63586 20 7.42667V18.8851C20 21.3884 17.1149 22.7906 15.1465 21.244L12.6178 19.2572C12.2552 18.9723 11.7448 18.9723 11.3822 19.2572L8.85347 21.244C6.88508 22.7906 4 21.3884 4 18.8851V7.42667C4 5.63586 4.17141 4.10082 5.19898 3.12219C5.71857 2.62734 6.3731 2.35454 7.0999 2.20071Z" />
  </svg>
}

export default SvgComponent

// vue/solid/bookmark.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-bookmark",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M7.0999 2.20071C7.81792 2.04874 8.66947 2 9.648 2H14.352C15.3305 2 16.1821 2.04874 16.9001 2.20071C17.6269 2.35454 18.2814 2.62734 18.801 3.12219C19.8286 4.10082 20 5.63586 20 7.42667V18.8851C20 21.3884 17.1149 22.7906 15.1465 21.244L12.6178 19.2572C12.2552 18.9723 11.7448 18.9723 11.3822 19.2572L8.85347 21.244C6.88508 22.7906 4 21.3884 4 18.8851V7.42667C4 5.63586 4.17141 4.10082 5.19898 3.12219C5.71857 2.62734 6.3731 2.35454 7.0999 2.20071Z"})
  ]))
}
