// react/outline/browser.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-browser" {...props}>
    <path d="M3 8.976C3 4.05476 4.05476 3 8.976 3H15.024C19.9452 3 21 4.05476 21 8.976V15.024C21 19.9452 19.9452 21 15.024 21H8.976C4.05476 21 3 19.9452 3 15.024V8.976Z" />
	<path d="M21 8L3 8" />
	<path d="M8 8L8 4" />
  </svg>
}

export default SvgComponent

// vue/solid/browser.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-browser",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M20 9C21.1046 9 22 9.89543 22 11V15.024C22 16.2771 21.9342 17.3524 21.7345 18.2508C21.5323 19.1607 21.1798 19.9494 20.5646 20.5646C19.9494 21.1798 19.1607 21.5323 18.2508 21.7345C17.3524 21.9342 16.2771 22 15.024 22H8.976C7.72287 22 6.64762 21.9342 5.74915 21.7345C4.83933 21.5323 4.05065 21.1798 3.43543 20.5646C2.82021 19.9494 2.46772 19.1607 2.26552 18.2508C2.06584 17.3524 2 16.2771 2 15.024V11C2 9.89543 2.89543 9 4 9L20 9Z"}), 
	_createElementVNode("path", {"d":"M9 5C9 6.10457 9.89543 7 11 7L20.6569 7C21.3362 7 21.8818 6.41224 21.7345 5.74915C21.5323 4.83933 21.1798 4.05065 20.5646 3.43543C19.9494 2.82021 19.1607 2.46772 18.2508 2.26552C17.3524 2.06584 16.2771 2 15.024 2H11C9.89543 2 9 2.89543 9 4L9 5Z"}), 
	_createElementVNode("path", {"d":"M4.99998 7.00004C6.10455 7.00004 6.99998 6.10461 6.99998 5.00004L6.99998 3.34314C6.99998 2.66388 6.41222 2.11819 5.74913 2.26556C4.83931 2.46776 4.05063 2.82025 3.43541 3.43547C2.82019 4.05069 2.4677 4.83937 2.2655 5.74919C2.11813 6.41228 2.66382 7.00004 3.34308 7.00004H4.99998Z"})
  ]))
}
