// react/outline/cloud-rain.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-cloud-rain" {...props}>
    <path d="M6.27126 16C4.31103 14.7751 3 12.5463 3 10C3 6.13401 6.02208 3 9.75 3C13.1779 3 16.009 5.64982 16.4425 9.08201C16.4575 9.20119 16.5708 9.28382 16.6895 9.26537C16.8724 9.23695 17.0595 9.22222 17.25 9.22222C19.3211 9.22222 21 10.9633 21 13.1111C21 14.2576 20.5216 15.2882 19.7605 16" />
	<path d="M10 15V20" />
	<path d="M13 15V21" />
	<path d="M16 15V20" />
  </svg>
}

export default SvgComponent

// vue/solid/cloud-rain.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-cloud-rain",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M9.75 2C5.43583 2 2 5.61631 2 10C2 12.8702 3.46667 15.3998 5.68559 16.8129C5.88136 16.9376 6.1052 17 6.3286 17H7.7C7.86569 17 8 16.8657 8 16.7V14C8 12.8954 8.89543 12 10 12C10.4751 12 10.9116 12.1657 11.2547 12.4424C11.3951 12.5557 11.6049 12.5557 11.7453 12.4424C12.0884 12.1657 12.5249 12 13 12C13.4751 12 13.9116 12.1657 14.2547 12.4424C14.3951 12.5557 14.6049 12.5557 14.7453 12.4424C15.0884 12.1657 15.5249 12 16 12C17.1046 12 18 12.8954 18 14V16.7C18 16.8657 18.1343 17 18.3 17H19.6815C19.982 17 20.2847 16.8866 20.5155 16.6616C21.4327 15.7678 22 14.5036 22 13.1111C22 10.5453 20.061 8.38918 17.5458 8.23146C17.4066 8.22274 17.287 8.12583 17.2531 7.99056C16.3933 4.56546 13.3817 2 9.75 2Z"}), 
	_createElementVNode("path", {"d":"M10 13C10.5523 13 11 13.4477 11 14V20C11 20.5523 10.5523 21 10 21C9.44772 21 9 20.5523 9 20V14C9 13.4477 9.44772 13 10 13Z"}), 
	_createElementVNode("path", {"d":"M13 13C13.5523 13 14 13.4477 14 14V21C14 21.5523 13.5523 22 13 22C12.4477 22 12 21.5523 12 21V14C12 13.4477 12.4477 13 13 13Z"}), 
	_createElementVNode("path", {"d":"M16 13C16.5523 13 17 13.4477 17 14V20C17 20.5523 16.5523 21 16 21C15.4477 21 15 20.5523 15 20V14C15 13.4477 15.4477 13 16 13Z"})
  ]))
}
