// react/solid/cursor-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-cursor-alt" {...props}>
    <path d="M13.4049 17.3737C12.1169 20.1754 7.94756 19.4443 7.6896 16.3716L7.10914 9.45749C6.89678 6.92797 9.72627 5.29437 11.8107 6.74304L17.5083 10.7028C20.0404 12.4626 18.5888 16.4388 15.5185 16.1534L14.7348 16.0805C14.3122 16.0412 13.9109 16.273 13.7336 16.6585L13.4049 17.3737Z" />
  </svg>
}

export default SvgComponent

// vue/solid/cursor-alt.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-cursor-alt",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M13.4049 17.3737C12.1169 20.1754 7.94756 19.4443 7.6896 16.3716L7.10914 9.45749C6.89678 6.92797 9.72627 5.29437 11.8107 6.74304L17.5083 10.7028C20.0404 12.4626 18.5888 16.4388 15.5185 16.1534L14.7348 16.0805C14.3122 16.0412 13.9109 16.273 13.7336 16.6585L13.4049 17.3737Z"})
  ]))
}
