// react/solid/divide-circle.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-divide-circle" {...props}>
    <path d="M12 9.01C11.4477 9.01 11 8.56229 11 8.01V8C11 7.44772 11.4477 7 12 7C12.5523 7 13 7.44772 13 8V8.01C13 8.56228 12.5523 9.01 12 9.01ZM6 12C6 11.4477 6.44772 11 7 11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H7C6.44772 13 6 12.5523 6 12ZM11 16.01C11 16.5623 11.4477 17.01 12 17.01C12.5523 17.01 13 16.5623 13 16.01V16C13 15.4477 12.5523 15 12 15C11.4477 15 11 15.4477 11 16V16.01ZM2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12Z" />
  </svg>
}

export default SvgComponent

// vue/solid/divide-circle.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-divide-circle",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 9.01C11.4477 9.01 11 8.56229 11 8.01V8C11 7.44772 11.4477 7 12 7C12.5523 7 13 7.44772 13 8V8.01C13 8.56228 12.5523 9.01 12 9.01ZM6 12C6 11.4477 6.44772 11 7 11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H7C6.44772 13 6 12.5523 6 12ZM11 16.01C11 16.5623 11.4477 17.01 12 17.01C12.5523 17.01 13 16.5623 13 16.01V16C13 15.4477 12.5523 15 12 15C11.4477 15 11 15.4477 11 16V16.01ZM2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12Z"})
  ]))
}
