// react/outline/document-remove.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-document-remove" {...props}>
    <path d="M9 13H15" />
	<path d="M9.648 3C5.82037 3 5 3.82037 5 7.648V16.352C5 20.1796 5.82037 21 9.648 21H14.352C18.1796 21 19 20.1796 19 16.352V8.06221C19 7.797 18.8946 7.54264 18.7071 7.35511L14.6449 3.29289C14.4574 3.10536 14.203 3 13.9378 3H9.648Z" />
  </svg>
}

export default SvgComponent

// vue/solid/document-remove.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-document-remove",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M7.09002 2.21181C7.81273 2.05119 8.66827 2 9.648 2H13.9378C14.4682 2 14.9769 2.21071 15.352 2.58579L19.4142 6.648C19.7893 7.02307 20 7.53178 20 8.06221V16.352C20 17.3317 19.9488 18.1873 19.7882 18.91C19.6251 19.644 19.336 20.3009 18.8185 20.8185C18.3009 21.336 17.644 21.6251 16.91 21.7882C16.1873 21.9488 15.3317 22 14.352 22H9.648C8.66827 22 7.81273 21.9488 7.09002 21.7882C6.35596 21.6251 5.6991 21.336 5.18153 20.8185C4.66396 20.3009 4.37495 19.644 4.21181 18.91C4.05119 18.1873 4 17.3317 4 16.352V7.648C4 6.66827 4.05119 5.81273 4.21181 5.09002C4.37495 4.35596 4.66396 3.6991 5.18153 3.18153C5.6991 2.66396 6.35596 2.37495 7.09002 2.21181ZM9 12C8.44772 12 8 12.4477 8 13C8 13.5523 8.44772 14 9 14H15C15.5523 14 16 13.5523 16 13C16 12.4477 15.5523 12 15 12H9Z"})
  ]))
}
