// react/solid/eye.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-eye" {...props}>
    <path d="M17.6692 6.31513C14.5937 3.22829 9.60573 3.22829 6.53019 6.31513L2.87279 9.98597C1.70907 11.154 1.70907 13.0462 2.87279 14.2142L6.33077 17.6849C9.40631 20.7717 14.3943 20.7717 17.4698 17.6849L21.1272 14.014C22.2909 12.846 22.2909 10.9538 21.1272 9.78583L17.6692 6.31513ZM12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8Z" />
  </svg>
}

export default SvgComponent

// vue/solid/eye.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-eye",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M17.6692 6.31513C14.5937 3.22829 9.60573 3.22829 6.53019 6.31513L2.87279 9.98597C1.70907 11.154 1.70907 13.0462 2.87279 14.2142L6.33077 17.6849C9.40631 20.7717 14.3943 20.7717 17.4698 17.6849L21.1272 14.014C22.2909 12.846 22.2909 10.9538 21.1272 9.78583L17.6692 6.31513ZM12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8Z"})
  ]))
}
