// react/outline/git-merge.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-git-merge" {...props}>
    <path d="M3 18C3 16.3431 4.34315 15 6 15C7.65685 15 9 16.3431 9 18C9 19.6569 7.65685 21 6 21C4.34315 21 3 19.6569 3 18Z" />
	<path d="M3 6C3 4.34315 4.34315 3 6 3C7.65685 3 9 4.34315 9 6C9 7.65685 7.65685 9 6 9C4.34315 9 3 7.65685 3 6Z" />
	<path d="M15 18C15 16.3431 16.3431 15 18 15C19.6569 15 21 16.3431 21 18C21 19.6569 19.6569 21 18 21C16.3431 21 15 19.6569 15 18Z" />
	<path d="M6 9L6 15" />
	<path d="M18 15L18 11.6758C18 7.00178 16.9424 6 12.008 6L9 6" />
  </svg>
}

export default SvgComponent

// vue/solid/git-merge.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-git-merge",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 18C2 20.2091 3.79086 22 6 22C8.20914 22 10 20.2091 10 18C10 16.1362 8.72523 14.5701 7 14.126L7 9.87398C8.40561 9.5122 9.5122 8.40561 9.87398 7L12.008 7C13.2201 7 14.1293 7.06271 14.82 7.20811C15.5022 7.35173 15.9041 7.5624 16.1667 7.81114C16.702 8.31818 17 9.30757 17 11.6758L17 14.126C15.2748 14.5701 14 16.1362 14 18C14 20.2091 15.7909 22 18 22C20.2091 22 22 20.2091 22 18C22 16.1362 20.7252 14.5701 19 14.126L19 11.6758C19 9.37002 18.7692 7.5215 17.5421 6.35914C16.9235 5.77319 16.1359 5.44129 15.232 5.25101C14.3366 5.06251 13.2631 5 12.008 5L9.87398 5C9.42994 3.27477 7.86384 2 6 2C3.79086 2 2 3.79086 2 6C2 7.86384 3.27477 9.42994 5 9.87398L5 14.126C3.27477 14.5701 2 16.1362 2 18Z"})
  ]))
}
