// react/outline/litecoin-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-litecoin-square" {...props}>
    <path d="M15.5 16H11.7749C10.4097 16 9.4458 14.6626 9.87748 13.3675L12 7" />
	<path d="M7.5 13L13.5 10.5" />
	<path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
  </svg>
}

export default SvgComponent

// vue/solid/litecoin-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-litecoin-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 12C2 3.765 3.765 2 12 2C20.235 2 22 3.765 22 12C22 20.235 20.235 22 12 22C3.765 22 2 20.235 2 12ZM12.3162 6.05132C12.8402 6.22596 13.1233 6.79228 12.9487 7.31623L12.0467 10.0222L13.1154 9.57692C13.6252 9.36451 14.2107 9.60558 14.4231 10.1154C14.6355 10.6252 14.3944 11.2107 13.8846 11.4231L11.208 12.5383L10.3874 15H15.5C16.0523 15 16.5 15.4477 16.5 16C16.5 16.5523 16.0523 17 15.5 17H9C8.67856 17 8.37671 16.8455 8.18876 16.5847C8.00081 16.3239 7.94967 15.9887 8.05132 15.6838L8.75976 13.5584L7.88462 13.9231C7.37481 14.1355 6.78934 13.8944 6.57692 13.3846C6.36451 12.8748 6.60558 12.2893 7.11538 12.0769L9.59847 11.0423L11.0513 6.68377C11.226 6.15983 11.7923 5.87667 12.3162 6.05132Z"})
  ]))
}
