// react/solid/more-horizontal-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-more-horizontal-square" {...props}>
    <path d="M12 2C3.765 2 2 3.765 2 12C2 20.235 3.765 22 12 22C20.235 22 22 20.235 22 12C22 3.765 20.235 2 12 2ZM8 11C7.44772 11 7 11.4477 7 12C7 12.5523 7.44772 13 8 13H8.01C8.56229 13 9.01 12.5523 9.01 12C9.01 11.4477 8.56229 11 8.01 11H8ZM11 12C11 11.4477 11.4477 11 12 11H12.01C12.5623 11 13.01 11.4477 13.01 12C13.01 12.5523 12.5623 13 12.01 13H12C11.4477 13 11 12.5523 11 12ZM16 11C15.4477 11 15 11.4477 15 12C15 12.5523 15.4477 13 16 13H16.01C16.5623 13 17.01 12.5523 17.01 12C17.01 11.4477 16.5623 11 16.01 11H16Z" />
  </svg>
}

export default SvgComponent

// vue/solid/more-horizontal-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-more-horizontal-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C3.765 2 2 3.765 2 12C2 20.235 3.765 22 12 22C20.235 22 22 20.235 22 12C22 3.765 20.235 2 12 2ZM8 11C7.44772 11 7 11.4477 7 12C7 12.5523 7.44772 13 8 13H8.01C8.56229 13 9.01 12.5523 9.01 12C9.01 11.4477 8.56229 11 8.01 11H8ZM11 12C11 11.4477 11.4477 11 12 11H12.01C12.5623 11 13.01 11.4477 13.01 12C13.01 12.5523 12.5623 13 12.01 13H12C11.4477 13 11 12.5523 11 12ZM16 11C15.4477 11 15 11.4477 15 12C15 12.5523 15.4477 13 16 13H16.01C16.5623 13 17.01 12.5523 17.01 12C17.01 11.4477 16.5623 11 16.01 11H16Z"})
  ]))
}
