// react/outline/more-vertical-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-vertical-square" {...props}>
    <path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
	<path d="M12.0049 16.005L12.0049 15.995" />
	<path d="M12.0049 12.005L12.0049 11.995" />
	<path d="M12.0049 8.005L12.0049 7.995" />
  </svg>
}

export default SvgComponent

// vue/solid/more-vertical-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-more-vertical-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C3.765 2 2 3.765 2 12C2 20.235 3.765 22 12 22C20.235 22 22 20.235 22 12C22 3.765 20.235 2 12 2ZM11.005 16.005C11.005 16.5573 11.4527 17.005 12.005 17.005C12.5573 17.005 13.005 16.5573 13.005 16.005V15.995C13.005 15.4427 12.5573 14.995 12.005 14.995C11.4527 14.995 11.005 15.4427 11.005 15.995V16.005ZM12.005 13.005C11.4527 13.005 11.005 12.5573 11.005 12.005V11.995C11.005 11.4427 11.4527 10.995 12.005 10.995C12.5573 10.995 13.005 11.4427 13.005 11.995V12.005C13.005 12.5573 12.5573 13.005 12.005 13.005ZM11.005 8.005C11.005 8.55729 11.4527 9.005 12.005 9.005C12.5573 9.005 13.005 8.55729 13.005 8.005V7.995C13.005 7.44272 12.5573 6.995 12.005 6.995C11.4527 6.995 11.005 7.44272 11.005 7.995V8.005Z"})
  ]))
}
