// react/outline/ruble-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-ruble-square" {...props}>
    <path d="M11 8V17" />
	<path d="M9 15H15" />
	<path d="M11 8H13.5C16.5 8 16.5 12 13.5 12H9" />
	<path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
  </svg>
}

export default SvgComponent

// vue/solid/ruble-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-ruble-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 11H13.5C14.0171 11 14.3146 10.8337 14.4804 10.6679C14.6556 10.4927 14.75 10.2526 14.75 10C14.75 9.74736 14.6556 9.50731 14.4804 9.33211C14.3146 9.16631 14.0171 9 13.5 9H12V11Z"}), 
	_createElementVNode("path", {"d":"M12 2C3.765 2 2 3.765 2 12C2 20.235 3.765 22 12 22C20.235 22 22 20.235 22 12C22 3.765 20.235 2 12 2ZM11 7C10.4477 7 10 7.44772 10 8V11H9C8.44771 11 8 11.4477 8 12C8 12.5523 8.44771 13 9 13H10V14H9C8.44771 14 8 14.4477 8 15C8 15.5523 8.44771 16 9 16H10V17C10 17.5523 10.4477 18 11 18C11.5523 18 12 17.5523 12 17V16H15C15.5523 16 16 15.5523 16 15C16 14.4477 15.5523 14 15 14H12V13H13.5C14.4829 13 15.3104 12.6663 15.8946 12.0821C16.4694 11.5073 16.75 10.7474 16.75 10C16.75 9.25264 16.4694 8.49269 15.8946 7.91789C15.3104 7.33369 14.4829 7 13.5 7H11Z"})
  ]))
}
