// react/solid/user-x.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-user-x" {...props}>
    <path d="M5 9.5C5 7.01472 7.01472 5 9.5 5C11.9853 5 14 7.01472 14 9.5C14 11.9853 11.9853 14 9.5 14C7.01472 14 5 11.9853 5 9.5Z" />
	<path d="M4.52885 15.773C5.75321 15.1886 7.39328 15 9.5 15C11.6067 15 13.2468 15.1886 14.4711 15.773C15.7635 16.3898 16.5474 17.4241 16.9661 18.9191C17.037 19.172 16.9953 19.4473 16.854 19.6607C16.7126 19.874 16.4884 20 16.25 20H2.75001C2.51158 20 2.28735 19.874 2.146 19.6607C2.00466 19.4473 1.96303 19.172 2.03388 18.9191C2.45258 17.4241 3.23654 16.3898 4.52885 15.773Z" />
	<path d="M16 3L21 8" />
	<path d="M21 3L16 8" />
  </svg>
}

export default SvgComponent

// vue/solid/user-x.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-user-x",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M5 9.5C5 7.01472 7.01472 5 9.5 5C11.9853 5 14 7.01472 14 9.5C14 11.9853 11.9853 14 9.5 14C7.01472 14 5 11.9853 5 9.5Z"}), 
	_createElementVNode("path", {"d":"M4.52885 15.773C5.75321 15.1886 7.39328 15 9.5 15C11.6067 15 13.2468 15.1886 14.4711 15.773C15.7635 16.3898 16.5474 17.4241 16.9661 18.9191C17.037 19.172 16.9953 19.4473 16.854 19.6607C16.7126 19.874 16.4884 20 16.25 20H2.75001C2.51158 20 2.28735 19.874 2.146 19.6607C2.00466 19.4473 1.96303 19.172 2.03388 18.9191C2.45258 17.4241 3.23654 16.3898 4.52885 15.773Z"}), 
	_createElementVNode("path", {"d":"M16 3L21 8"}), 
	_createElementVNode("path", {"d":"M21 3L16 8"})
  ]))
}
