// react/outline/watches.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-watches" {...props}>
    <path d="M6 11.1936C6 6.91667 6.91667 6 11.1936 6H12.8064C17.0833 6 18 6.91667 18 11.1936V12.8064C18 17.0833 17.0833 18 12.8064 18H11.1936C6.91667 18 6 17.0833 6 12.8064V11.1936Z" />
	<path d="M9 6V5C9 3.89543 9.89543 3 11 3H13C14.1046 3 15 3.89543 15 5V6" />
	<path d="M15 18L15 19C15 20.1046 14.1046 21 13 21L11 21C9.89543 21 9 20.1046 9 19L9 18" />
  </svg>
}

export default SvgComponent

// vue/solid/watches.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-watches",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M5 11.0592C5 6.06945 6.06945 5 11.0592 5H12.9408C17.9306 5 19 6.06945 19 11.0592V12.9408C19 17.9306 17.9306 19 12.9408 19H11.0592C6.06945 19 5 17.9306 5 12.9408V11.0592Z"}), 
	_createElementVNode("path", {"d":"M8.44883 19.9335C8.30306 19.9186 8.18763 20.0568 8.24588 20.1913C8.70681 21.2555 9.76648 22 11 22H13C14.2336 22 15.2933 21.2555 15.7542 20.1913C15.8124 20.0568 15.697 19.9186 15.5512 19.9335C15.0606 19.9837 14.5447 20 14.016 20H9.98404C9.45543 20 8.93945 19.9837 8.44883 19.9335Z"}), 
	_createElementVNode("path", {"d":"M8.24588 3.80871C8.18763 3.94318 8.30306 4.08147 8.44883 4.06655C8.93945 4.01632 9.45543 4 9.98404 4H14.016C14.5447 4 15.0606 4.01632 15.5512 4.06655C15.697 4.08147 15.8124 3.94318 15.7542 3.80871C15.2933 2.74452 14.2336 2 13 2H11C9.76648 2 8.70681 2.74452 8.24588 3.80871Z"})
  ]))
}
