// react/solid/zap.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-zap" {...props}>
    <path d="M13.5715 3.04167C13.9953 3.16806 14.2857 3.55776 14.2857 3.99996V9.39996H18C18.3673 9.39996 18.7051 9.60132 18.8797 9.92445C19.0544 10.2476 19.0378 10.6404 18.8366 10.9477L12.5509 20.5477C12.3087 20.9177 11.8522 21.0846 11.4285 20.9582C11.0047 20.8319 10.7143 20.4422 10.7143 20V14.6H7C6.63269 14.6 6.29495 14.3986 6.12029 14.0755C5.94563 13.7523 5.96218 13.3595 6.16338 13.0522L12.4491 3.45217C12.6913 3.08222 13.1478 2.91529 13.5715 3.04167Z" />
  </svg>
}

export default SvgComponent

// vue/solid/zap.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-zap",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M13.5715 3.04167C13.9953 3.16806 14.2857 3.55776 14.2857 3.99996V9.39996H18C18.3673 9.39996 18.7051 9.60132 18.8797 9.92445C19.0544 10.2476 19.0378 10.6404 18.8366 10.9477L12.5509 20.5477C12.3087 20.9177 11.8522 21.0846 11.4285 20.9582C11.0047 20.8319 10.7143 20.4422 10.7143 20V14.6H7C6.63269 14.6 6.29495 14.3986 6.12029 14.0755C5.94563 13.7523 5.96218 13.3595 6.16338 13.0522L12.4491 3.45217C12.6913 3.08222 13.1478 2.91529 13.5715 3.04167Z"})
  ]))
}
