// vue/solid/alarm.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-alarm",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM14.4453 14.8321C14.9048 15.1384 15.5257 15.0142 15.8321 14.5547C16.1384 14.0952 16.0142 13.4743 15.5547 13.1679L13 11.4648V7C13 6.44772 12.5523 6 12 6C11.4477 6 11 6.44772 11 7V11.5V11.5196C11 12.1541 11.3171 12.7466 11.8451 13.0986L14.4453 14.8321Z"}), 
	_createElementVNode("path", {"d":"M4.70711 2.29289C5.09763 2.68342 5.09763 3.31658 4.70711 3.70711L3.70711 4.70711C3.31658 5.09763 2.68342 5.09763 2.29289 4.70711C1.90237 4.31658 1.90237 3.68342 2.29289 3.29289L3.29289 2.29289C3.68342 1.90237 4.31658 1.90237 4.70711 2.29289Z"}), 
	_createElementVNode("path", {"d":"M19.2929 2.29289C18.9024 2.68342 18.9024 3.31658 19.2929 3.70711L20.2929 4.70711C20.6834 5.09763 21.3166 5.09763 21.7071 4.70711C22.0976 4.31658 22.0976 3.68342 21.7071 3.29289L20.7071 2.29289C20.3166 1.90237 19.6834 1.90237 19.2929 2.29289Z"})
  ]))
}

// react/outline/alarm.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-alarm" {...props}>
    <path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
	<path d="M12 7L12 11.5L12 11.5196C12 11.8197 12.15 12.1 12.3998 12.2665V12.2665L15 14" />
	<path d="M3 4L4 3" />
	<path d="M21 4L20 3" />
  </svg>
}

export default SvgComponent
