// svelte/outline/align-arrow-right.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-align-arrow-right" {...$$props}>
    <path d="M3 3L3 21" />
	<path d="M16 12L7 12" />
	<path d="M13 15L16 12L13 9" />
</svg>
}

export default SvgComponent

// react/outline/align-arrow-right.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-align-arrow-right" {...props}>
    <path d="M3 3L3 21" />
	<path d="M16 12L7 12" />
	<path d="M13 15L16 12L13 9" />
  </svg>
}

export default SvgComponent
