// vue/solid/align-vertical-center.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-align-vertical-center",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 3C2 2.44772 2.44772 2 3 2L21 2C21.5523 2 22 2.44772 22 3C22 3.55228 21.5523 4 21 4L3 4C2.44772 4 2 3.55228 2 3Z"}), 
	_createElementVNode("path", {"d":"M2 21C2 20.4477 2.44772 20 3 20L21 20C21.5523 20 22 20.4477 22 21C22 21.5523 21.5523 22 21 22L3 22C2.44772 22 2 21.5523 2 21Z"}), 
	_createElementVNode("path", {"d":"M8.43089 6.1581C8.97783 6.03654 9.61367 6 10.32 6H13.68C14.3863 6 15.0222 6.03654 15.5691 6.1581C16.1274 6.28217 16.6524 6.50772 17.0724 6.92764C17.4923 7.34756 17.7178 7.87259 17.8419 8.43089C17.9635 8.97783 18 9.61367 18 10.32V13.68C18 14.3863 17.9635 15.0222 17.8419 15.5691C17.7178 16.1274 17.4923 16.6524 17.0724 17.0724C16.6524 17.4923 16.1274 17.7178 15.5691 17.8419C15.0222 17.9635 14.3863 18 13.68 18H10.32C9.61367 18 8.97783 17.9635 8.43089 17.8419C7.87259 17.7178 7.34756 17.4923 6.92764 17.0724C6.50772 16.6524 6.28217 16.1274 6.1581 15.5691C6.03654 15.0222 6 14.3863 6 13.68V10.32C6 9.61367 6.03654 8.97783 6.1581 8.43089C6.28217 7.87259 6.50772 7.34756 6.92764 6.92764C7.34756 6.50772 7.87259 6.28217 8.43089 6.1581Z"})
  ]))
}

// react/outline/align-vertical-center.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-align-vertical-center" {...props}>
    <path d="M21 3L3 3" />
	<path d="M21 21L3 21" />
	<path d="M7 10.32C7 7.58598 7.58598 7 10.32 7H13.68C16.414 7 17 7.58598 17 10.32V13.68C17 16.414 16.414 17 13.68 17H10.32C7.58598 17 7 16.414 7 13.68V10.32Z" />
  </svg>
}

export default SvgComponent
