// svelte/outline/arrow-up-left.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-left" {...$$props}>
    <path d="M9.17151 9.17151L14.8284 14.8284" />
	<path d="M13.4143 9.17163L9.50009 9.17163L9.17167 9.17163L9.17167 9.50006L9.17167 13.4143" />
</svg>
}

export default SvgComponent

// react/outline/arrow-up-left.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-left" {...props}>
    <path d="M9.17151 9.17151L14.8284 14.8284" />
	<path d="M13.4143 9.17163L9.50009 9.17163L9.17167 9.17163L9.17167 9.50006L9.17167 13.4143" />
  </svg>
}

export default SvgComponent
