// svelte/outline/arrow-up-left-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-left-alt" {...$$props}>
    <path d="M6.34303 6.34315L17.6567 17.6569" />
	<path d="M14.8284 6.34314L6.71019 6.34314L6.34309 6.34314L6.34309 6.74407L6.34309 14.8284" />
</svg>
}

export default SvgComponent

// react/outline/arrow-up-left-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-left-alt" {...props}>
    <path d="M6.34303 6.34315L17.6567 17.6569" />
	<path d="M14.8284 6.34314L6.71019 6.34314L6.34309 6.34314L6.34309 6.74407L6.34309 14.8284" />
  </svg>
}

export default SvgComponent
