// svelte/outline/arrow-down-left.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-down-left" {...$$props}>
    <path d="M9.5 14.5L15 9" />
	<path d="M14 15L9.32833 15C9.147 15 9 14.853 9 14.6716L9 10" />
</svg>
}

export default SvgComponent

// react/outline/arrow-down-left.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-down-left" {...props}>
    <path d="M9.5 14.5L15 9" />
	<path d="M14 15L9.32833 15C9.147 15 9 14.853 9 14.6716L9 10" />
  </svg>
}

export default SvgComponent
