// vue/solid/bangladeshi-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-bangladeshi-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 12C2 3.765 3.765 2 12 2C20.235 2 22 3.765 22 12C22 20.235 20.235 22 12 22C3.765 22 2 20.235 2 12ZM8 11C8 10.4477 8.44771 10 9 10H10C10 8.9882 9.72288 8.50258 9.51624 8.27941C9.29572 8.04125 9.06508 8 9 8C8.44771 8 8 7.55228 8 7C8 6.44772 8.44771 6 9 6C9.60159 6 10.3709 6.25875 10.9838 6.92059C11.6104 7.59742 12 8.6118 12 10H15C15.5523 10 16 10.4477 16 11C16 11.5523 15.5523 12 15 12H12V14.5C12 15.0171 12.1663 15.3146 12.3321 15.4804C12.5073 15.6556 12.7474 15.75 13 15.75C13.2526 15.75 13.4927 15.6556 13.6679 15.4804C13.8337 15.3146 14 15.0171 14 14.5C14 13.9477 14.4477 13.5 15 13.5C15.5523 13.5 16 13.9477 16 14.5C16 15.4829 15.6663 16.3104 15.0821 16.8946C14.5073 17.4694 13.7474 17.75 13 17.75C12.2526 17.75 11.4927 17.4694 10.9179 16.8946C10.3337 16.3104 10 15.4829 10 14.5V12H9C8.44771 12 8 11.5523 8 11Z"})
  ]))
}

// react/outline/bangladeshi-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-bangladeshi-square" {...props}>
    <path d="M9 11H15" />
	<path d="M9 7C9.66667 7 11 7.6 11 10C11 12.4 11 14 11 14.5C11 17.5 15 17.5 15 14.5" />
	<path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
  </svg>
}

export default SvgComponent
