// svelte/outline/chevron-left.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-chevron-left" {...$$props}>
    <path d="M13 9L10.3003 11.6997V11.6997C10.1344 11.8656 10.1344 12.1344 10.3003 12.3003V12.3003L13 15" />
</svg>
}

export default SvgComponent

// react/outline/chevron-left.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-chevron-left" {...props}>
    <path d="M13 9L10.3003 11.6997V11.6997C10.1344 11.8656 10.1344 12.1344 10.3003 12.3003V12.3003L13 15" />
  </svg>
}

export default SvgComponent
