// svelte/outline/corner-right-up.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-right-up" {...$$props}>
    <path d="M7.50007 16.476C12.4213 16.476 13.4761 15.4212 13.4761 10.5L13.4761 9" />
	<path d="M16.4761 11.5L13.4761 8.5L10.4761 11.5" />
</svg>
}

export default SvgComponent

// react/outline/corner-right-up.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-right-up" {...props}>
    <path d="M7.50007 16.476C12.4213 16.476 13.4761 15.4212 13.4761 10.5L13.4761 9" />
	<path d="M16.4761 11.5L13.4761 8.5L10.4761 11.5" />
  </svg>
}

export default SvgComponent
