// vue/solid/document-off.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-document-off",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M19 14V8.06221C19 7.797 18.8946 7.54264 18.7071 7.35511L14.6449 3.29289C14.4574 3.10536 14.203 3 13.9378 3H9.648C9.42163 3 9.20578 3.00287 9 3.00906"}), 
	_createElementVNode("path", {"d":"M3.70711 2.29289C3.31658 1.90237 2.68342 1.90237 2.29289 2.29289C1.90237 2.68342 1.90237 3.31658 2.29289 3.70711L4.12778 5.542C4.03194 6.16632 4 6.87046 4 7.648V16.352C4 17.3317 4.05119 18.1873 4.21181 18.91C4.37495 19.644 4.66396 20.3009 5.18153 20.8185C5.6991 21.336 6.35596 21.6251 7.09002 21.7882C7.81273 21.9488 8.66827 22 9.648 22H14.352C15.7836 22 16.9984 21.8947 17.9269 21.4453C18.4164 21.2083 18.7979 20.892 19.0917 20.5059L20.2929 21.7071C20.6834 22.0976 21.3166 22.0976 21.7071 21.7071C22.0976 21.3166 22.0976 20.6834 21.7071 20.2929L3.70711 2.29289Z"})
  ]))
}

// react/outline/document-off.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-document-off" {...props}>
    <path d="M19 14V8.06221C19 7.797 18.8946 7.54264 18.7071 7.35511L14.6449 3.29289C14.4574 3.10536 14.203 3 13.9378 3H9.648C9.42163 3 9.20578 3.00287 9 3.00906" />
	<path d="M5.26719 5C5.07064 5.66055 5 6.5248 5 7.648V16.352C5 20.1796 5.82037 21 9.648 21H14.352C17.2044 21 18.3867 20.5444 18.8041 18.7282" />
	<path d="M3 3L21 21" />
  </svg>
}

export default SvgComponent
