// svelte/outline/download.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-download" {...$$props}>
    <path d="M21 14C20.0427 17.0763 17.58 18 12 18C6.41998 18 3.95728 17.1433 3 14.067" />
	<path d="M12 14L12 6" />
	<path d="M9 11L12 14L15 11" />
</svg>
}

export default SvgComponent

// react/outline/download.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-download" {...props}>
    <path d="M21 14C20.0427 17.0763 17.58 18 12 18C6.41998 18 3.95728 17.1433 3 14.067" />
	<path d="M12 14L12 6" />
	<path d="M9 11L12 14L15 11" />
  </svg>
}

export default SvgComponent
