// vue/solid/folder-off.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-folder-off",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M8.98389 4H9.92952C10.5982 4 11.2227 4.3342 11.5936 4.8906L12.4062 6.1094C12.7771 6.6658 13.4016 7 14.0703 7C15.9646 7 17.8144 7 19.1257 7C20.1806 7 21.0127 7.82095 21.0028 8.8758C21.0011 9.05376 20.9999 9.20638 20.9999 9.312V14.688C20.9999 15.1651 20.9887 15.6014 20.9632 16"}), 
	_createElementVNode("path", {"d":"M3.70711 2.29289C3.31658 1.90237 2.68342 1.90237 2.29289 2.29289C1.90237 2.68342 1.90237 3.31658 2.29289 3.70711L3.11031 4.52452C2.76628 4.93432 2.52121 5.42273 2.35307 5.97989C2.08024 6.8839 2 7.99898 2 9.31199V14.688C2 15.8044 2.05852 16.7698 2.23866 17.5804C2.42133 18.4023 2.74209 19.1251 3.30848 19.6915C3.87488 20.2579 4.59764 20.5787 5.41959 20.7613C6.23018 20.9415 7.19557 21 8.312 21H15.688C17.0462 21 18.2236 20.9173 19.1809 20.5951L20.2929 21.7071C20.6834 22.0976 21.3166 22.0976 21.7071 21.7071C22.0976 21.3166 22.0976 20.6834 21.7071 20.2929L3.70711 2.29289Z"})
  ]))
}

// react/outline/folder-off.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-folder-off" {...props}>
    <path d="M4.5 4.6405C3.32778 5.34053 3 6.72548 3 9.31199V14.688C3 19.0624 3.93757 20 8.312 20H15.688C17.4759 20 18.6897 19.8434 19.5 19.3595" />
	<path d="M8.98389 4H9.92952C10.5982 4 11.2227 4.3342 11.5936 4.8906L12.4062 6.1094C12.7771 6.6658 13.4016 7 14.0703 7C15.9646 7 17.8144 7 19.1257 7C20.1806 7 21.0127 7.82095 21.0028 8.8758C21.0011 9.05376 20.9999 9.20638 20.9999 9.312V14.688C20.9999 15.1651 20.9887 15.6014 20.9632 16" />
	<path d="M3 3L21 21" />
  </svg>
}

export default SvgComponent
