// vue/solid/git-fork.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-git-fork",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 6C2 3.79086 3.79086 2 6 2C8.20914 2 10 3.79086 10 6C10 7.82793 8.77388 9.36948 7.09921 9.84707C7.19043 10.347 7.33066 10.5391 7.4564 10.6405C7.70076 10.8375 8.24008 11 9.65202 11H14.348C15.76 11 16.2993 10.8375 16.5436 10.6405C16.6694 10.5391 16.8096 10.347 16.9008 9.84708C15.2261 9.3695 14 7.82794 14 6C14 3.79086 15.7909 2 18 2C20.2091 2 22 3.79086 22 6C22 7.89339 20.6845 9.47952 18.9176 9.89425C18.7966 10.8116 18.5042 11.6289 17.7989 12.1975C16.9427 12.8878 15.7125 13 14.348 13H13V14.126C14.7252 14.5701 16 16.1362 16 18C16 20.2091 14.2091 22 12 22C9.79086 22 8 20.2091 8 18C8 16.1362 9.27477 14.5701 11 14.126V13H9.65202C8.28755 13 7.05736 12.8878 6.20111 12.1975C5.49583 11.6289 5.20346 10.8116 5.08243 9.89426C3.31553 9.47954 2 7.8934 2 6Z"})
  ]))
}

// react/outline/git-fork.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-git-fork" {...props}>
    <path d="M6 3C7.65685 3 9 4.34315 9 6C9 7.65685 7.65685 9 6 9C4.34315 9 3 7.65685 3 6C3 4.34315 4.34315 3 6 3Z" />
	<path d="M18 3C19.6569 3 21 4.34315 21 6C21 7.65685 19.6569 9 18 9C16.3431 9 15 7.65685 15 6C15 4.34315 16.3431 3 18 3Z" />
	<path d="M12 15C13.6569 15 15 16.3431 15 18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18C9 16.3431 10.3431 15 12 15Z" />
	<path d="M6.01221 9C6.11299 11.4506 6.87561 12 9.65202 12H14.348C17.1244 12 17.887 11.4506 17.9878 9" />
	<path d="M12 15V12" />
  </svg>
}

export default SvgComponent
