// svelte/outline/hash.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hash" {...$$props}>
    <path d="M8 10H16" />
	<path d="M8 14H16" />
	<path d="M7 10H17" />
	<path d="M7 14H17" />
	<path d="M9 17L11 7" />
	<path d="M13 17L15 7" />
</svg>
}

export default SvgComponent

// react/outline/hash.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hash" {...props}>
    <path d="M8 10H16" />
	<path d="M8 14H16" />
	<path d="M7 10H17" />
	<path d="M7 14H17" />
	<path d="M9 17L11 7" />
	<path d="M13 17L15 7" />
  </svg>
}

export default SvgComponent
