// svelte/outline/litecoin.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-litecoin" {...$$props}>
    <path d="M15.5 16H11.7749C10.4097 16 9.4458 14.6626 9.87748 13.3675L12 7" />
	<path d="M7.5 13L13.5 10.5" />
</svg>
}

export default SvgComponent

// react/outline/litecoin.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-litecoin" {...props}>
    <path d="M15.5 16H11.7749C10.4097 16 9.4458 14.6626 9.87748 13.3675L12 7" />
	<path d="M7.5 13L13.5 10.5" />
  </svg>
}

export default SvgComponent
