// vue/solid/litecoin-circle.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-litecoin-circle",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12.9485 7.31626C13.1231 6.79231 12.8399 6.22599 12.316 6.05134C11.7921 5.8767 11.2257 6.15986 11.0511 6.6838L9.59825 11.0423L7.11516 12.077C6.60536 12.2894 6.36428 12.8748 6.5767 13.3846C6.78911 13.8944 7.37459 14.1355 7.88439 13.9231L8.80935 13.5377C8.52651 15.3147 9.8978 17 11.7746 17H15.4998C16.0521 17 16.4998 16.5523 16.4998 16C16.4998 15.4477 16.0521 15 15.4998 15H11.7746C11.0921 15 10.6101 14.3313 10.8259 13.6838L11.2078 12.5384L13.8844 11.4231C14.3942 11.2107 14.6353 10.6252 14.4228 10.1154C14.2104 9.60561 13.625 9.36453 13.1152 9.57695L12.0465 10.0222L12.9485 7.31626ZM2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12Z"})
  ]))
}

// react/outline/litecoin-circle.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-litecoin-circle" {...props}>
    <path d="M15.5 16H11.7749C10.4097 16 9.4458 14.6626 9.87748 13.3675L12 7" />
	<path d="M7.5 13L13.5 10.5" />
	<path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
  </svg>
}

export default SvgComponent
