// svelte/outline/maximaize-square.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-maximaize-square" {...$$props}>
    <path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
	<path d="M8 12L8 16L12 16" />
	<path d="M16 12L16.0001 8L12 8" />
</svg>
}

export default SvgComponent

// react/outline/maximaize-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-maximaize-square" {...props}>
    <path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
	<path d="M8 12L8 16L12 16" />
	<path d="M16 12L16.0001 8L12 8" />
  </svg>
}

export default SvgComponent
