// svelte/outline/more-horizontal.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-horizontal" {...$$props}>
    <path d="M8 12H8.01" />
	<path d="M12 12H12.01" />
	<path d="M16 12H16.01" />
</svg>
}

export default SvgComponent

// react/outline/more-horizontal.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-horizontal" {...props}>
    <path d="M8 12H8.01" />
	<path d="M12 12H12.01" />
	<path d="M16 12H16.01" />
  </svg>
}

export default SvgComponent
