// svelte/outline/pause.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-pause" {...$$props}>
    <path d="M14 9L14 15" />
	<path d="M10 9L10 15" />
</svg>
}

export default SvgComponent

// react/outline/pause.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-pause" {...props}>
    <path d="M14 9L14 15" />
	<path d="M10 9L10 15" />
  </svg>
}

export default SvgComponent
