// svelte/outline/play.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-play" {...$$props}>
    <path d="M10 9V15L15 12L10 9Z" />
</svg>
}

export default SvgComponent

// react/outline/play.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-play" {...props}>
    <path d="M10 9V15L15 12L10 9Z" />
  </svg>
}

export default SvgComponent
