// vue/solid/rows.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-rows",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 15.024C2 16.2771 2.06584 17.3524 2.26552 18.2508C2.46772 19.1607 2.82021 19.9493 3.43543 20.5646C4.05065 21.1798 4.83933 21.5323 5.74915 21.7345C6.64762 21.9342 7.72287 22 8.976 22L15.024 22C16.2771 22 17.3524 21.9342 18.2508 21.7345C19.1607 21.5323 19.9494 21.1798 20.5646 20.5646C21.1798 19.9494 21.5323 19.1607 21.7345 18.2508C21.9342 17.3524 22 16.2771 22 15.024L22 15C22 13.8954 21.1046 13 20 13L4 13C2.89543 13 2 13.8954 2 15L2 15.024Z"}), 
	_createElementVNode("path", {"d":"M22 8.976C22 7.72287 21.9342 6.64763 21.7345 5.74916C21.5323 4.83933 21.1798 4.05065 20.5646 3.43543C19.9494 2.82021 19.1607 2.46772 18.2508 2.26552C17.3524 2.06584 16.2771 2 15.024 2L8.976 2C7.72287 2 6.64763 2.06584 5.74916 2.26552C4.83933 2.46772 4.05065 2.82021 3.43543 3.43543C2.82021 4.05065 2.46772 4.83933 2.26552 5.74916C2.06584 6.64762 2 7.72287 2 8.976L2 9C2 10.1046 2.89543 11 4 11L20 11C21.1046 11 22 10.1046 22 9L22 8.976Z"})
  ]))
}

// react/outline/rows.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-rows" {...props}>
    <path d="M15.024 3C19.9452 3 21 4.05476 21 8.976L21 15.024C21 19.9452 19.9452 21 15.024 21L8.976 21C4.05476 21 3 19.9452 3 15.024L3 8.976C3 4.05476 4.05476 3 8.976 3L15.024 3Z" />
	<path d="M21 12L3 12" />
  </svg>
}

export default SvgComponent
