// svelte/outline/ruble.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-ruble" {...$$props}>
    <path d="M11 8V17" />
	<path d="M9 15H15" />
	<path d="M11 8H13.5C16.5 8 16.5 12 13.5 12H9" />
</svg>
}

export default SvgComponent

// react/outline/ruble.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-ruble" {...props}>
    <path d="M11 8V17" />
	<path d="M9 15H15" />
	<path d="M11 8H13.5C16.5 8 16.5 12 13.5 12H9" />
  </svg>
}

export default SvgComponent
