// vue/solid/yen-square.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-yen-square",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M2 12C2 3.765 3.765 2 12 2C20.235 2 22 3.765 22 12C22 20.235 20.235 22 12 22C3.765 22 2 20.235 2 12ZM8.4453 6.16795C8.90483 5.8616 9.5257 5.98577 9.83205 6.4453L12 9.69722L14.1679 6.4453C14.4743 5.98577 15.0952 5.8616 15.5547 6.16795C16.0142 6.4743 16.1384 7.09517 15.8321 7.5547L13.5352 11H15C15.5523 11 16 11.4477 16 12C16 12.5523 15.5523 13 15 13H13V14H15C15.5523 14 16 14.4477 16 15C16 15.5523 15.5523 16 15 16H13V17C13 17.5523 12.5523 18 12 18C11.4477 18 11 17.5523 11 17V16H9C8.44771 16 8 15.5523 8 15C8 14.4477 8.44771 14 9 14H11V13H9C8.44771 13 8 12.5523 8 12C8 11.4477 8.44771 11 9 11H10.4648L8.16795 7.5547C7.8616 7.09517 7.98577 6.4743 8.4453 6.16795Z"})
  ]))
}

// react/outline/yen-square.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-yen-square" {...props}>
    <path d="M9 7L12 11.5L15 7" />
	<path d="M12 11.5V17" />
	<path d="M9 12H15" />
	<path d="M9 15H15" />
	<path d="M3 12C3 4.5885 4.5885 3 12 3C19.4115 3 21 4.5885 21 12C21 19.4115 19.4115 21 12 21C4.5885 21 3 19.4115 3 12Z" />
  </svg>
}

export default SvgComponent
