// vue/solid/arrow-up-left-circle.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-arrow-up-left-circle",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM8 14C8 14.5523 8.44772 15 9 15C9.55228 15 10 14.5523 10 14V11.4142L14.2929 15.7071C14.6834 16.0976 15.3166 16.0976 15.7071 15.7071C16.0976 15.3166 16.0976 14.6834 15.7071 14.2929L11.4142 10H14C14.5523 10 15 9.55228 15 9C15 8.44772 14.5523 8 14 8H9.32833C8.59458 8 8 8.59489 8 9.32837V14Z"})
  ]))
}

// react/solid/arrow-up-left-circle.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-arrow-up-left-circle" {...props}>
    <path d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM8 14C8 14.5523 8.44772 15 9 15C9.55228 15 10 14.5523 10 14V11.4142L14.2929 15.7071C14.6834 16.0976 15.3166 16.0976 15.7071 15.7071C16.0976 15.3166 16.0976 14.6834 15.7071 14.2929L11.4142 10H14C14.5523 10 15 9.55228 15 9C15 8.44772 14.5523 8 14 8H9.32833C8.59458 8 8 8.59489 8 9.32837V14Z" />
  </svg>
}

export default SvgComponent
