// vue/solid/chart-bubble.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-chart-bubble",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M10 8C10 4.68629 12.6863 2 16 2C19.3137 2 22 4.68629 22 8C22 11.3137 19.3137 14 16 14C12.6863 14 10 11.3137 10 8Z"}), 
	_createElementVNode("path", {"d":"M2 15.5C2 13.0147 4.01472 11 6.5 11C8.98528 11 11 13.0147 11 15.5C11 17.9853 8.98528 20 6.5 20C4.01472 20 2 17.9853 2 15.5Z"}), 
	_createElementVNode("path", {"d":"M13 18.5C13 16.567 14.567 15 16.5 15C18.433 15 20 16.567 20 18.5C20 20.433 18.433 22 16.5 22C14.567 22 13 20.433 13 18.5Z"})
  ]))
}

// react/solid/chart-bubble.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-chart-bubble" {...props}>
    <path d="M10 8C10 4.68629 12.6863 2 16 2C19.3137 2 22 4.68629 22 8C22 11.3137 19.3137 14 16 14C12.6863 14 10 11.3137 10 8Z" />
	<path d="M2 15.5C2 13.0147 4.01472 11 6.5 11C8.98528 11 11 13.0147 11 15.5C11 17.9853 8.98528 20 6.5 20C4.01472 20 2 17.9853 2 15.5Z" />
	<path d="M13 18.5C13 16.567 14.567 15 16.5 15C18.433 15 20 16.567 20 18.5C20 20.433 18.433 22 16.5 22C14.567 22 13 20.433 13 18.5Z" />
  </svg>
}

export default SvgComponent
