// vue/solid/chart-pie.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-chart-pie",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M9.79606 2.24387C11.6528 1.82605 13 3.42223 13 4.99998V9.99998C13 10.5523 13.4477 11 14 11H19C20.5777 11 22.1739 12.3472 21.7561 14.2039C20.752 18.6661 16.7665 22 12 22C6.47715 22 2 17.5228 2 12C2 7.23347 5.33387 3.248 9.79606 2.24387Z"}), 
	_createElementVNode("path", {"d":"M21.904 7.83946C22.1158 9.10696 21.05 10 20 10L16 10C14.8954 10 14 9.1046 14 8.00003L14 4.00003C14 2.95002 14.893 1.88423 16.1605 2.09595C19.0976 2.58655 21.4134 4.90239 21.904 7.83946Z"})
  ]))
}

// react/solid/chart-pie.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-chart-pie" {...props}>
    <path d="M9.79606 2.24387C11.6528 1.82605 13 3.42223 13 4.99998V9.99998C13 10.5523 13.4477 11 14 11H19C20.5777 11 22.1739 12.3472 21.7561 14.2039C20.752 18.6661 16.7665 22 12 22C6.47715 22 2 17.5228 2 12C2 7.23347 5.33387 3.248 9.79606 2.24387Z" />
	<path d="M21.904 7.83946C22.1158 9.10696 21.05 10 20 10L16 10C14.8954 10 14 9.1046 14 8.00003L14 4.00003C14 2.95002 14.893 1.88423 16.1605 2.09595C19.0976 2.58655 21.4134 4.90239 21.904 7.83946Z" />
  </svg>
}

export default SvgComponent
