// vue/solid/play.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-play",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M9.5073 8.1298C9.82081 7.95229 10.2056 7.95715 10.5145 8.14251L15.5145 11.1425C15.8157 11.3232 16 11.6487 16 12C16 12.3513 15.8157 12.6768 15.5145 12.8575L10.5145 15.8575C10.2056 16.0429 9.82081 16.0477 9.5073 15.8702C9.19379 15.6927 9 15.3603 9 15V9C9 8.63973 9.19379 8.30731 9.5073 8.1298Z"})
  ]))
}

// react/solid/play.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-play" {...props}>
    <path d="M9.5073 8.1298C9.82081 7.95229 10.2056 7.95715 10.5145 8.14251L15.5145 11.1425C15.8157 11.3232 16 11.6487 16 12C16 12.3513 15.8157 12.6768 15.5145 12.8575L10.5145 15.8575C10.2056 16.0429 9.82081 16.0477 9.5073 15.8702C9.19379 15.6927 9 15.3603 9 15V9C9 8.63973 9.19379 8.30731 9.5073 8.1298Z" />
  </svg>
}

export default SvgComponent
