// vue/solid/user.js
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export default function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("svg", {
    "xmlns": "http://www.w3.org/2000/svg", 
	"width": "24", 
	"height": "24", 
	"viewBox": "0 0 24 24", 
	"fill": "currentColor", 
	"stroke": "none", 
	"fill-rule": "evenodd", 
	"clip-rule": "evenodd", 
	"class": "scarlab scarlab-user",
    ..._ctx
  }, [
    _createElementVNode("path", {"d":"M6 8C6 4.68629 8.68629 2 12 2C15.3137 2 18 4.68629 18 8C18 11.3137 15.3137 14 12 14C8.68629 14 6 11.3137 6 8Z"}), 
	_createElementVNode("path", {"d":"M5.37536 16.9064C7.00836 16.2124 9.19613 16 12 16C14.8039 16 16.9917 16.2124 18.6247 16.9064C20.3535 17.6411 21.3992 18.8867 21.9562 20.7074C22.049 21.0106 21.9925 21.3398 21.8039 21.5947C21.6154 21.8496 21.3171 22 21 22H3.00001C2.68294 22 2.38466 21.8496 2.19609 21.5947C2.00751 21.3398 1.951 21.0106 2.04377 20.7074C2.60084 18.8867 3.64651 17.6411 5.37536 16.9064Z"})
  ]))
}

// react/solid/user.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" fill-rule="evenodd" clip-rule="evenodd" class="scarlab scarlab-user" {...props}>
    <path d="M6 8C6 4.68629 8.68629 2 12 2C15.3137 2 18 4.68629 18 8C18 11.3137 15.3137 14 12 14C8.68629 14 6 11.3137 6 8Z" />
	<path d="M5.37536 16.9064C7.00836 16.2124 9.19613 16 12 16C14.8039 16 16.9917 16.2124 18.6247 16.9064C20.3535 17.6411 21.3992 18.8867 21.9562 20.7074C22.049 21.0106 21.9925 21.3398 21.8039 21.5947C21.6154 21.8496 21.3171 22 21 22H3.00001C2.68294 22 2.38466 21.8496 2.19609 21.5947C2.00751 21.3398 1.951 21.0106 2.04377 20.7074C2.60084 18.8867 3.64651 17.6411 5.37536 16.9064Z" />
  </svg>
}

export default SvgComponent
