// react/outline/alert.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-alert" {...props}>
    <path d="M12 8L12 13" />
	<path d="M12 16V15.9888" />
  </svg>
}

export default SvgComponent

// svelte/outline/alert.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-alert" {...$$props}>
    <path d="M12 8L12 13" />
	<path d="M12 16V15.9888" />
</svg>
}

export default SvgComponent
