// react/outline/alert-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-alert-alt" {...props}>
    <path d="M12 5L12 15" />
	<path d="M12 19.0112V19" />
  </svg>
}

export default SvgComponent

// svelte/outline/alert-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-alert-alt" {...$$props}>
    <path d="M12 5L12 15" />
	<path d="M12 19.0112V19" />
</svg>
}

export default SvgComponent
