// react/outline/align-arrow-down.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-align-arrow-down" {...props}>
    <path d="M21 3L3 3" />
	<path d="M12 16L12 7" />
	<path d="M9 13L10.5858 14.5858C11.3668 15.3668 12.6332 15.3668 13.4142 14.5858L15 13" />
  </svg>
}

export default SvgComponent

// svelte/outline/align-arrow-down.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-align-arrow-down" {...$$props}>
    <path d="M21 3L3 3" />
	<path d="M12 16L12 7" />
	<path d="M9 13L10.5858 14.5858C11.3668 15.3668 12.6332 15.3668 13.4142 14.5858L15 13" />
</svg>
}

export default SvgComponent
