// react/outline/arrow-left-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-left-alt" {...props}>
    <path d="M4 12L20 12" />
	<path d="M10 6L4.0625 11.9375L4 12L4.0625 12.0625L10 18" />
  </svg>
}

export default SvgComponent

// svelte/outline/arrow-left-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-left-alt" {...$$props}>
    <path d="M4 12L20 12" />
	<path d="M10 6L4.0625 11.9375L4 12L4.0625 12.0625L10 18" />
</svg>
}

export default SvgComponent
