// react/outline/arrow-left.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-left" {...props}>
    <path d="M8 12L16 12" />
	<path d="M11 9L8.08704 11.913L8 12L8.08704 12.087L11 15" />
  </svg>
}

export default SvgComponent

// svelte/outline/arrow-left.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-left" {...$$props}>
    <path d="M8 12L16 12" />
	<path d="M11 9L8.08704 11.913L8 12L8.08704 12.087L11 15" />
</svg>
}

export default SvgComponent
