// react/outline/arrow-up-right.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-right" {...props}>
    <path d="M14.5 9.5L9 15" />
	<path d="M10 9H14.6717C14.853 9 15 9.14703 15 9.32837V14" />
  </svg>
}

export default SvgComponent

// svelte/outline/arrow-up-right.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-right" {...$$props}>
    <path d="M14.5 9.5L9 15" />
	<path d="M10 9H14.6717C14.853 9 15 9.14703 15 9.32837V14" />
</svg>
}

export default SvgComponent
