// react/outline/arrow-right-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-right-alt" {...props}>
    <path d="M20 12L4 12" />
	<path d="M14 18L19.9375 12.0625L20 12L19.9375 11.9375L14 6" />
  </svg>
}

export default SvgComponent

// svelte/outline/arrow-right-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-right-alt" {...$$props}>
    <path d="M20 12L4 12" />
	<path d="M14 18L19.9375 12.0625L20 12L19.9375 11.9375L14 6" />
</svg>
}

export default SvgComponent
