// react/outline/arrow-up-right-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-right-alt" {...props}>
    <path d="M17.657 6.34315L6.34326 17.6569" />
	<path d="M17.6567 14.8284L17.6567 6.74402L17.6567 6.34309L17.3365 6.34309L9.17146 6.34309" />
  </svg>
}

export default SvgComponent

// svelte/outline/arrow-up-right-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-arrow-up-right-alt" {...$$props}>
    <path d="M17.657 6.34315L6.34326 17.6569" />
	<path d="M17.6567 14.8284L17.6567 6.74402L17.6567 6.34309L17.3365 6.34309L9.17146 6.34309" />
</svg>
}

export default SvgComponent
