// react/outline/bangladeshi.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-bangladeshi" {...props}>
    <path d="M9 11H15" />
	<path d="M9 7C9.66667 7 11 7.6 11 10C11 12.4 11 14 11 14.5C11 17.5 15 17.5 15 14.5" />
  </svg>
}

export default SvgComponent

// svelte/outline/bangladeshi.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-bangladeshi" {...$$props}>
    <path d="M9 11H15" />
	<path d="M9 7C9.66667 7 11 7.6 11 10C11 12.4 11 14 11 14.5C11 17.5 15 17.5 15 14.5" />
</svg>
}

export default SvgComponent
