// react/outline/brightness.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-brightness" {...props}>
    <path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
	<path d="M12 3V21" />
	<path d="M12 8.00002L16.5 4.40002" />
	<path d="M12 13L19.5 7" />
	<path d="M12 18L20.75 11" />
  </svg>
}

export default SvgComponent

// svelte/outline/brightness.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-brightness" {...$$props}>
    <path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
	<path d="M12 3V21" />
	<path d="M12 8.00002L16.5 4.40002" />
	<path d="M12 13L19.5 7" />
	<path d="M12 18L20.75 11" />
</svg>
}

export default SvgComponent
