// react/outline/calendar-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-calendar-alt" {...props}>
    <path d="M3 10.312C3 5.93757 3.93757 5 8.312 5H15.688C20.0624 5 21 5.93757 21 10.312V15.688C21 20.0624 20.0624 21 15.688 21H8.312C3.93757 21 3 20.0624 3 15.688V10.312Z" />
	<path d="M6 5L6 3" />
	<path d="M18 5L18 3" />
	<path d="M3.5 9H20.5" />
  </svg>
}

export default SvgComponent

// svelte/outline/calendar-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-calendar-alt" {...$$props}>
    <path d="M3 10.312C3 5.93757 3.93757 5 8.312 5H15.688C20.0624 5 21 5.93757 21 10.312V15.688C21 20.0624 20.0624 21 15.688 21H8.312C3.93757 21 3 20.0624 3 15.688V10.312Z" />
	<path d="M6 5L6 3" />
	<path d="M18 5L18 3" />
	<path d="M3.5 9H20.5" />
</svg>
}

export default SvgComponent
