// react/outline/chart-bar-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-chart-bar-alt" {...props}>
    <path d="M12 3L12 21" />
	<path d="M17 7L17 21" />
	<path d="M7 10L7 21" />
  </svg>
}

export default SvgComponent

// svelte/outline/chart-bar-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-chart-bar-alt" {...$$props}>
    <path d="M12 3L12 21" />
	<path d="M17 7L17 21" />
	<path d="M7 10L7 21" />
</svg>
}

export default SvgComponent
