// react/outline/corner-up-left.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-up-left" {...props}>
    <path d="M15.976 16.976C15.976 12.0548 14.9212 11 10 11H8.5" />
	<path d="M11 8L8 11L11 14" />
  </svg>
}

export default SvgComponent

// svelte/outline/corner-up-left.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-up-left" {...$$props}>
    <path d="M15.976 16.976C15.976 12.0548 14.9212 11 10 11H8.5" />
	<path d="M11 8L8 11L11 14" />
</svg>
}

export default SvgComponent
