// react/outline/corner-up-right.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-up-right" {...props}>
    <path d="M8.00007 16.976C8.00007 12.0548 9.05484 11 13.9761 11H15.4761" />
	<path d="M12.9761 8L15.9761 11L12.9761 14" />
  </svg>
}

export default SvgComponent

// svelte/outline/corner-up-right.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-up-right" {...$$props}>
    <path d="M8.00007 16.976C8.00007 12.0548 9.05484 11 13.9761 11H15.4761" />
	<path d="M12.9761 8L15.9761 11L12.9761 14" />
</svg>
}

export default SvgComponent
