// react/outline/corner-down-right.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-down-right" {...props}>
    <path d="M8.00007 7.99995C8.00007 12.9212 9.05484 13.976 13.9761 13.976H15.4761" />
	<path d="M12.9761 16.976L15.9761 13.976L12.9761 10.976" />
  </svg>
}

export default SvgComponent

// svelte/outline/corner-down-right.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-corner-down-right" {...$$props}>
    <path d="M8.00007 7.99995C8.00007 12.9212 9.05484 13.976 13.9761 13.976H15.4761" />
	<path d="M12.9761 16.976L15.9761 13.976L12.9761 10.976" />
</svg>
}

export default SvgComponent
