// react/outline/divide.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-divide" {...props}>
    <path d="M7 12H17" />
	<path d="M12 8.01001L12 8.00001" />
	<path d="M12 16.01L12 16" />
  </svg>
}

export default SvgComponent

// svelte/outline/divide.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-divide" {...$$props}>
    <path d="M7 12H17" />
	<path d="M12 8.01001L12 8.00001" />
	<path d="M12 16.01L12 16" />
</svg>
}

export default SvgComponent
