// react/outline/equal-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-equal-alt" {...props}>
    <path d="M5 10H19" />
	<path d="M5 14H19" />
  </svg>
}

export default SvgComponent

// svelte/outline/equal-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-equal-alt" {...$$props}>
    <path d="M5 10H19" />
	<path d="M5 14H19" />
</svg>
}

export default SvgComponent
