// react/outline/hash-alt.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hash-alt" {...props}>
    <path d="M13 21L17 3" />
	<path d="M7 21L11 3" />
	<path d="M20 9L4 9" />
	<path d="M4 15L20 15" />
  </svg>
}

export default SvgComponent

// svelte/outline/hash-alt.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hash-alt" {...$$props}>
    <path d="M13 21L17 3" />
	<path d="M7 21L11 3" />
	<path d="M20 9L4 9" />
	<path d="M4 15L20 15" />
</svg>
}

export default SvgComponent
