// react/outline/hrivnia.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hrivnia" {...props}>
    <path d="M10 6.99997C14 4.99995 16.9816 8.67884 12 12C7.58389 14.9442 10.5 19 14 17" />
	<path d="M16 10.5L8 10.5" />
	<path d="M16 13.5L8 13.5" />
  </svg>
}

export default SvgComponent

// svelte/outline/hrivnia.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-hrivnia" {...$$props}>
    <path d="M10 6.99997C14 4.99995 16.9816 8.67884 12 12C7.58389 14.9442 10.5 19 14 17" />
	<path d="M16 10.5L8 10.5" />
	<path d="M16 13.5L8 13.5" />
</svg>
}

export default SvgComponent
