// react/outline/italic.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-italic" {...props}>
    <path d="M9 4H19" />
	<path d="M14 4L10 20" />
	<path d="M5 20H15" />
  </svg>
}

export default SvgComponent

// svelte/outline/italic.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-italic" {...$$props}>
    <path d="M9 4H19" />
	<path d="M14 4L10 20" />
	<path d="M5 20H15" />
</svg>
}

export default SvgComponent
