// react/outline/maximaize.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-maximaize" {...props}>
    <path d="M8 12L8 16L12 16" />
	<path d="M16 12L16.0001 8L12 8" />
  </svg>
}

export default SvgComponent

// svelte/outline/maximaize.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-maximaize" {...$$props}>
    <path d="M8 12L8 16L12 16" />
	<path d="M16 12L16.0001 8L12 8" />
</svg>
}

export default SvgComponent
