// react/outline/minimaize.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-minimaize" {...props}>
    <path d="M11 17L10.9999 13.5V13.5C10.9999 13.2239 10.7761 13 10.5 13V13L7 13" />
	<path d="M13 7L13 10.5V10.5C13 10.7761 13.2239 11 13.5 11V11L17 11" />
  </svg>
}

export default SvgComponent

// svelte/outline/minimaize.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-minimaize" {...$$props}>
    <path d="M11 17L10.9999 13.5V13.5C10.9999 13.2239 10.7761 13 10.5 13V13L7 13" />
	<path d="M13 7L13 10.5V10.5C13 10.7761 13.2239 11 13.5 11V11L17 11" />
</svg>
}

export default SvgComponent
