// react/outline/more-horizontal-circle.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-horizontal-circle" {...props}>
    <path d="M8 12H8.01" />
	<path d="M12 12H12.01" />
	<path d="M16 12H16.01" />
	<path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
  </svg>
}

export default SvgComponent

// svelte/outline/more-horizontal-circle.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-horizontal-circle" {...$$props}>
    <path d="M8 12H8.01" />
	<path d="M12 12H12.01" />
	<path d="M16 12H16.01" />
	<path d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" />
</svg>
}

export default SvgComponent
