// react/outline/more-vertical.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-vertical" {...props}>
    <path d="M12.0049 16.005L12.0049 15.995" />
	<path d="M12.0049 12.005L12.0049 11.995" />
	<path d="M12.0049 8.005L12.0049 7.995" />
  </svg>
}

export default SvgComponent

// svelte/outline/more-vertical.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-more-vertical" {...$$props}>
    <path d="M12.0049 16.005L12.0049 15.995" />
	<path d="M12.0049 12.005L12.0049 11.995" />
	<path d="M12.0049 8.005L12.0049 7.995" />
</svg>
}

export default SvgComponent
