// react/outline/overline.js
import * as React from "react"

function SvgComponent(props) {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-overline" {...props}>
    <path d="M7 8V15C7 17.7614 9.23858 20 12 20C14.7614 20 17 17.7614 17 15V8" />
	<path d="M5 4H19" />
  </svg>
}

export default SvgComponent

// svelte/outline/overline.svelte
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="scarlab scarlab-overline" {...$$props}>
    <path d="M7 8V15C7 17.7614 9.23858 20 12 20C14.7614 20 17 17.7614 17 15V8" />
	<path d="M5 4H19" />
</svg>
}

export default SvgComponent
